version: '3.8'

services:
  apps:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL : "postgresql://postgres:postgres@localhost:5432/mydb?schema=public"
    depends_on:
      - db
    volumes:
      - /apps:/app
      - /app/node_module
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    restart : always
    environment:
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : postgres
      POSTGRES_DB : mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver : local